use crate::parser::ParsedAgent;

pub fn to_snake_case(name: &str) -> String {
    name.replace('-', "_")
}

pub fn to_pascal_case(name: &str) -> String {
    name.split('-')
        .map(|segment| {
            let mut chars = segment.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
            }
        })
        .collect()
}

pub fn to_screaming_snake_case(name: &str) -> String {
    name.replace('-', "_").to_uppercase()
}

/// Produce a raw string literal `r#...#"content"#...#` using the minimum number
/// of `#` characters needed so that the closing delimiter `"##...#` does not
/// appear inside `content`.  This prevents any agent body content from
/// prematurely terminating the literal (e.g. when the body contains Rust code
/// examples that themselves include raw string literals).
pub fn raw_str_literal(content: &str) -> String {
    let mut hashes = 1usize;
    loop {
        let terminator = "\"".to_string() + &"#".repeat(hashes);
        if !content.contains(&terminator) {
            break;
        }
        hashes += 1;
        assert!(
            hashes <= 16,
            "Agent content requires more than 16 '#' characters — cannot safely embed in raw string literal"
        );
    }
    let h = "#".repeat(hashes);
    format!("r{h}\"{content}\"{h}")
}

pub fn generate_agent_file(agent: &ParsedAgent, timestamp: &str) -> String {
    let constant = to_screaming_snake_case(&agent.name);

    let caps_str = agent
        .capabilities
        .iter()
        .map(|c| format!(r#""{c}""#))
        .collect::<Vec<_>>()
        .join(", ");
    let capabilities_literal = format!("&[{}]", caps_str);

    let header = format!(
        "//! Auto-generated by bmad-converter. DO NOT EDIT.\n\
         //! Source: agents/{}.md\n\
         //! Generated: {}\n\n",
        agent.name, timestamp
    );

    let imports = "use bmad_types::{AgentMetadata, GenerationParams, SuggestedConfig};\n\n";

    let name_lit = raw_str_literal(&agent.name);
    let display_name_lit = raw_str_literal(&agent.display_name);
    let description_lit = raw_str_literal(&agent.description);
    let executor_name_lit = raw_str_literal(&agent.executor_name);

    let static_block = format!(
        "pub static {constant}: AgentMetadata = AgentMetadata {{\n\
         \x20\x20\x20\x20name: {name},\n\
         \x20\x20\x20\x20display_name: {display_name},\n\
         \x20\x20\x20\x20description: {description},\n\
         \x20\x20\x20\x20executor_name: {executor_name},\n\
         \x20\x20\x20\x20capabilities: {caps},\n\
         }};\n\n",
        constant = constant,
        name = name_lit,
        display_name = display_name_lit,
        description = description_lit,
        executor_name = executor_name_lit,
        caps = capabilities_literal,
    );

    let metadata_fn = format!(
        "pub fn metadata() -> &'static AgentMetadata {{\n    &{constant}\n}}\n\n",
        constant = constant,
    );

    let body_lit = raw_str_literal(&format!("{}\n", agent.body));
    let system_prompt = format!("pub const SYSTEM_PROMPT: &str = {body_lit};\n\n");

    let suggested_params_fn = match agent.temperature {
        Some(temp) => format!(
            "pub fn suggested_params() -> Option<GenerationParams> {{\n    \
             Some(GenerationParams {{ model: None, temperature: Some({temp}_f32), max_tokens: None }})\n}}\n\n"
        ),
        None => "pub fn suggested_params() -> Option<GenerationParams> {\n    None\n}\n\n".to_string(),
    };

    let suggested_config_fn = if agent.model_tier.is_some() || agent.max_turns.is_some() || agent.permission_mode.is_some() {
        let model_tier = match &agent.model_tier {
            Some(v) => format!("Some(\"{}\".to_string())", v),
            None => "None".to_string(),
        };
        let max_turns = match agent.max_turns {
            Some(v) => format!("Some({})", v),
            None => "None".to_string(),
        };
        let permission_mode = match &agent.permission_mode {
            Some(v) => format!("Some(\"{}\".to_string())", v),
            None => "None".to_string(),
        };
        format!(
            "pub fn suggested_config() -> Option<SuggestedConfig> {{\n    \
             Some(SuggestedConfig {{\n        \
             model_tier: {model_tier},\n        \
             max_turns: {max_turns},\n        \
             permission_mode: {permission_mode},\n        \
             allowed_tools: None,\n    \
             }})\n}}\n"
        )
    } else {
        "pub fn suggested_config() -> Option<SuggestedConfig> {\n    None\n}\n".to_string()
    };

    format!("{header}{imports}{static_block}{metadata_fn}{system_prompt}{suggested_params_fn}{suggested_config_fn}")
}

pub fn generate_mod_file(agents: &[ParsedAgent]) -> String {
    let mut sorted: Vec<&ParsedAgent> = agents.iter().collect();
    sorted.sort_by(|a, b| a.name.cmp(&b.name));

    let mut out = String::new();
    out.push_str("//! Auto-generated module index. DO NOT EDIT.\n");
    out.push_str("//! Generated by bmad-converter.\n\n");

    for agent in &sorted {
        out.push_str(&format!("pub mod {};\n", to_snake_case(&agent.name)));
    }
    out.push('\n');

    for agent in &sorted {
        let snake = to_snake_case(&agent.name);
        let constant = to_screaming_snake_case(&agent.name);
        out.push_str(&format!("pub use {}::{};\n", snake, constant));
    }
    out.push('\n');

    out.push_str("use bmad_types::{AgentMetadata, GenerationParams, SuggestedConfig};\n\n");

    out.push_str("pub fn all_agents() -> Vec<&'static AgentMetadata> {\n");
    out.push_str("    vec![\n");
    for agent in &sorted {
        let constant = to_screaming_snake_case(&agent.name);
        let snake = to_snake_case(&agent.name);
        out.push_str(&format!("        &{}::{},\n", snake, constant));
    }
    out.push_str("    ]\n");
    out.push_str("}\n\n");

    out.push_str(
        "pub fn all_agent_entries() -> Vec<(&'static AgentMetadata, &'static str, Option<GenerationParams>, Option<SuggestedConfig>)> {\n",
    );
    out.push_str("    vec![\n");
    for agent in &sorted {
        let snake = to_snake_case(&agent.name);
        out.push_str(&format!(
            "        ({snake}::metadata(), {snake}::SYSTEM_PROMPT, {snake}::suggested_params(), {snake}::suggested_config()),\n",
            snake = snake,
        ));
    }
    out.push_str("    ]\n");
    out.push_str("}\n");

    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_agent(name: &str) -> ParsedAgent {
        ParsedAgent {
            name: name.to_string(),
            display_name: format!("{} Display", name),
            description: format!("{} description", name),
            executor_name: format!("bmad/{}", name),
            capabilities: vec!["cap-a".to_string(), "cap-b".to_string()],
            body: format!("# {}\n\nBody text for {}.", name, name),
            temperature: None,
            model_tier: None,
            max_turns: None,
            permission_mode: None,
        }
    }

    #[test]
    fn snake_case_replaces_hyphens() {
        assert_eq!(to_snake_case("tech-writer"), "tech_writer");
        assert_eq!(to_snake_case("bmad-master"), "bmad_master");
        assert_eq!(to_snake_case("architect"), "architect");
        assert_eq!(to_snake_case("ux-designer"), "ux_designer");
    }

    #[test]
    fn pascal_case_capitalizes_segments() {
        assert_eq!(to_pascal_case("tech-writer"), "TechWriter");
        assert_eq!(to_pascal_case("bmad-master"), "BmadMaster");
        assert_eq!(to_pascal_case("architect"), "Architect");
        assert_eq!(to_pascal_case("ux-designer"), "UxDesigner");
    }

    #[test]
    fn screaming_snake_case_uppercases() {
        assert_eq!(to_screaming_snake_case("tech-writer"), "TECH_WRITER");
        assert_eq!(to_screaming_snake_case("bmad-master"), "BMAD_MASTER");
        assert_eq!(to_screaming_snake_case("architect"), "ARCHITECT");
        assert_eq!(to_screaming_snake_case("ux-designer"), "UX_DESIGNER");
    }

    #[test]
    fn generate_agent_file_starts_with_header() {
        let agent = make_agent("architect");
        let result = generate_agent_file(&agent, "2026-03-17T10:30:00Z");
        assert!(result.starts_with("//! Auto-generated by bmad-converter. DO NOT EDIT."));
        assert!(result.contains("//! Source: agents/architect.md"));
        assert!(result.contains("//! Generated: 2026-03-17T10:30:00Z"));
    }

    #[test]
    fn generate_agent_file_contains_constant_and_metadata() {
        let agent = make_agent("tech-writer");
        let result = generate_agent_file(&agent, "2026-03-17T10:30:00Z");
        assert!(result.contains("pub static TECH_WRITER: AgentMetadata"));
        assert!(result.contains("pub fn metadata()"));
        assert!(result.contains("pub const SYSTEM_PROMPT"));
    }

    #[test]
    fn raw_str_literal_single_hash_for_normal_content() {
        let result = raw_str_literal("hello world");
        assert!(result.starts_with("r#"));
        assert!(result.ends_with("#"));
        assert!(result.contains("hello world"));
    }

    #[test]
    fn raw_str_literal_escalates_to_double_hash_when_needed() {
        let content = format!("ends with {}", "\x22#");
        let result = raw_str_literal(&content);
        assert!(result.starts_with("r##"), "should escalate to double hash");
        assert!(result.ends_with("##"));
        assert!(result.contains(&content));
    }

    #[test]
    fn raw_str_literal_escalates_to_triple_hash_when_needed() {
        let content = format!("contains {}{} sequence", "\x22", "##");
        let result = raw_str_literal(&content);
        assert!(result.starts_with("r###"), "should escalate to triple hash");
        assert!(result.ends_with("###"));
        assert!(result.contains(&content));
    }

    #[test]
    fn generate_agent_file_uses_raw_string_literals() {
        let agent = make_agent("architect");
        let result = generate_agent_file(&agent, "2026-03-17T10:30:00Z");
        assert!(result.contains("r#") || result.contains("r##"));
    }

    #[test]
    fn generate_agent_file_all_fields_use_raw_string_literals() {
        let agent = make_agent("tech-writer");
        let result = generate_agent_file(&agent, "2026-03-17T10:30:00Z");
        assert!(
            !result.contains("id:"),
            "id field should not be present (removed)"
        );
        assert!(
            result.contains("name: r"),
            "name field should use raw string literal"
        );
        assert!(
            result.contains("executor_name: r"),
            "executor_name field should use raw string literal"
        );
    }

    #[test]
    fn generate_mod_file_has_pub_mod_and_pub_use() {
        let agents = vec![make_agent("architect"), make_agent("developer")];
        let result = generate_mod_file(&agents);
        assert!(result.contains("pub mod architect;"));
        assert!(result.contains("pub mod developer;"));
        assert!(result.contains("pub use architect::ARCHITECT;"));
        assert!(result.contains("pub use developer::DEVELOPER;"));
    }

    #[test]
    fn generate_mod_file_has_all_agents_fn() {
        let agents = vec![make_agent("architect"), make_agent("qa")];
        let result = generate_mod_file(&agents);
        assert!(result.contains("pub fn all_agents()"));
        assert!(result.contains("Vec<&'static AgentMetadata>"));
        assert!(result.contains("&architect::ARCHITECT"));
        assert!(result.contains("&qa::QA"));
    }

    #[test]
    fn generate_mod_file_has_all_agent_entries_fn() {
        let agents = vec![make_agent("architect"), make_agent("qa")];
        let result = generate_mod_file(&agents);
        assert!(result.contains("pub fn all_agent_entries()"));
        assert!(result.contains("SYSTEM_PROMPT"));
        assert!(result.contains("suggested_params()"));
        assert!(result.contains("architect::metadata()"));
        assert!(result.contains("qa::metadata()"));
    }

    #[test]
    fn generate_mod_file_alphabetical_order() {
        let agents = vec![make_agent("zebra"), make_agent("alpha")];
        let result = generate_mod_file(&agents);
        let alpha_pos = result.find("pub mod alpha").unwrap();
        let zebra_pos = result.find("pub mod zebra").unwrap();
        assert!(alpha_pos < zebra_pos, "alpha should appear before zebra");
    }

    #[test]
    fn generate_agent_file_emits_suggested_params_none_when_no_temperature() {
        let agent = make_agent("architect");
        let result = generate_agent_file(&agent, "2026-03-17T10:30:00Z");
        assert!(result.contains("pub fn suggested_params()"));
        assert!(result.contains("None"));
    }

    #[test]
    fn generate_agent_file_emits_suggested_params_some_when_temperature_specified() {
        let mut agent = make_agent("qa");
        agent.temperature = Some(0.7);
        let result = generate_agent_file(&agent, "2026-03-17T10:30:00Z");
        assert!(result.contains("pub fn suggested_params()"));
        assert!(result.contains("Some(GenerationParams"));
        assert!(result.contains("0.7"));
    }
}
