use tempfile::TempDir;

/// Locate the bmad-converter binary.
/// When running via `cargo test --workspace`, Cargo builds all workspace binaries
/// into target/debug/. We find the converter at that known path.
fn converter_bin() -> std::path::PathBuf {
    // CARGO_MANIFEST_DIR for the root package IS the workspace root
    let workspace_root = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    // Cargo builds workspace binaries to target/debug during `cargo test`
    let debug_bin = workspace_root
        .join("target")
        .join("debug")
        .join("bmad-converter");
    if debug_bin.exists() {
        return debug_bin;
    }
    // Fall back to release (e.g. after cargo build --release)
    workspace_root
        .join("target")
        .join("release")
        .join("bmad-converter")
}

fn write_agent(dir: &std::path::Path, name: &str) -> std::path::PathBuf {
    let path = dir.join(format!("{}.md", name));
    let content = format!(
        r#"---
name: {name}
displayName: "{Name} Agent"
description: "Test {name} agent"
executor: bmad/{name}
capabilities:
  - {name}-capability
---

# {Name}

You are {Name}, a test agent.
"#,
        name = name,
        Name = {
            let mut c = name.chars();
            match c.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
            }
        }
    );
    std::fs::write(&path, content).unwrap();
    path
}

#[test]
fn converter_produces_one_file_per_agent_plus_mod() {
    let input_dir = TempDir::new().unwrap();
    let output_dir = TempDir::new().unwrap();

    write_agent(input_dir.path(), "alpha");
    write_agent(input_dir.path(), "beta");

    let status = std::process::Command::new(converter_bin())
        .arg("--input")
        .arg(input_dir.path())
        .arg("--output")
        .arg(output_dir.path())
        .status()
        .expect("failed to run bmad-converter");

    assert!(status.success(), "Converter exited with non-zero status");

    let mod_rs = output_dir.path().join("mod.rs");
    assert!(mod_rs.exists(), "mod.rs must exist");

    let alpha_rs = output_dir.path().join("alpha.rs");
    assert!(alpha_rs.exists(), "alpha.rs must exist");

    let beta_rs = output_dir.path().join("beta.rs");
    assert!(beta_rs.exists(), "beta.rs must exist");

    let alpha_content = std::fs::read_to_string(&alpha_rs).unwrap();
    assert!(
        alpha_content.starts_with("//! Auto-generated by bmad-converter. DO NOT EDIT."),
        "Generated file must start with standard header"
    );
}

#[test]
fn converter_clean_overwrites_stale_files() {
    let input_dir = TempDir::new().unwrap();
    let output_dir = TempDir::new().unwrap();

    let stale = output_dir.path().join("stale_agent.rs");
    std::fs::write(&stale, "// stale").unwrap();

    write_agent(input_dir.path(), "fresh");

    let status = std::process::Command::new(converter_bin())
        .arg("--input")
        .arg(input_dir.path())
        .arg("--output")
        .arg(output_dir.path())
        .status()
        .expect("failed to run bmad-converter");

    assert!(status.success());
    assert!(
        !stale.exists(),
        "Stale file must be removed during clean regeneration"
    );
}
